---
abstract: 'Sample module for a talk at YAPC::NA::2010'
author:
  - 'Kevin Falcone  C<< <falcone@bestpractical.com> >>'
  - 'Kevin Falcone <falcone@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.97'
license: gplv2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Sample-YAPC2010
no_index:
  directory:
    - html
    - inc
requires:
  Test::More: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.01
